name: Release Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: [self-hosted, deploy-release]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build
        run: docker build . --file Dockerfile --tag xivrepo/frontend-release:${{ github.sha }} --build-arg VERSION_ID=${{ github.sha }} --build-arg WEBSITE_URL="https://preview.xivrepo.com" --build-arg API_URL="https://preview.xivrepo.com" --build-arg CDN_URL="https://preview.xivrepo.com"

      -
        name: Deploy
        run: |
          pushd /compose/release-frontend-server
          TAG=${{ github.sha }} docker-compose up -d
          popd
