name: Develop Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: [self-hosted, deploy-develop]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build
        run: docker build . --file Dockerfile --tag xivrepo/frontend-develop:${{ github.sha }} --build-arg VERSION_ID=${{ github.sha }} --build-arg WEBSITE_URL="https://dev.xivrepo.com" --build-arg API_URL="https://dev.xivrepo.com" --build-arg CDN_URL="https://dev.xivrepo.com"

      -
        name: Deploy
        run: |
          pushd /compose/develop-frontend-server
          TAG=${{ github.sha }} docker-compose up -d
          popd
